version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: go-record-signer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recordsigner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  initdb:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /app/initdb
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  signer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/signer
    env_file:
      - .env
    depends_on:
      initdb:
        condition: service_completed_successfully

volumes:
  postgres_data: 