version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: go-record-signer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recordsigner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    container_name: go-record-signer-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream --http_port 8222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 5s
      retries: 3

  initdb:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /app/initdb
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/dispatcher
    env_file:
      - .env
    depends_on:
      initdb:
        condition: service_completed_successfully
      nats:
        condition: service_healthy

volumes:
  postgres_data: 