version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: go-record-signer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recordsigner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    container_name: go-record-signer-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream --http_port 8222"

  #nats image does not have shell, so we need to use alpine to check health
  nats-healthcheck:
    image: alpine
    depends_on:
      - nats
    command: /bin/sh -c "apk add --no-cache curl && tail -f /dev/null"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://nats:8222/healthz || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s

  initdb:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /app/initdb
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/dispatcher
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      nats-healthcheck:
        condition: service_healthy
  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/worker
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      nats-healthcheck:
        condition: service_healthy

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/worker
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      nats-healthcheck:
        condition: service_healthy

volumes:
  postgres_data: